name: Build and Cache
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    continue-on-error: ${{ matrix.os == 'ubuntu-latest' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            sandbox = false
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build codex
        run: nix build .#codex -L

      - name: Smoke test
        run: ./result/bin/codex --version || true
