name: Build and Cache
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            sandbox = false
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        if: github.ref == 'refs/heads/main'
        with:
          name: caseymatt
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build codex
        run: nix build .#codex -L

      - name: Push to Cachix
        if: github.ref == 'refs/heads/main'
        run: nix build .#codex --json | jq -r '.[].outputs.out' | cachix push caseymatt

      - name: Smoke test
        run: ./result/bin/codex --version || true
