name: Test Pull Request

on:
  pull_request:
    paths:
      - 'codex-nix/package.nix'
      - 'codex-nix/flake.nix'
      - 'codex-nix/sources.json'

jobs:
  test-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build package
        run: |
          nix build .#codex --print-build-logs || true
          # Don't fail PRs if sources.json hasn't been populated yet
          if [ ! -e result/bin/codex ]; then echo "Skipped binary tests"; exit 0; fi

      - name: Smoke test codex
        if: ${{ hashFiles('result/bin/codex') != '' }}
        run: |
          ./result/bin/codex --version || true
          test -f ./result/bin/codex
          test -x ./result/bin/codex
          test -f ./result/bin/codex-bin
